name = "automotora-mtg"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "worker.js"

[[d1_databases]]
binding = "DB"
database_name = "mtg-automotora"
database_id = "9868463e-4dc9-45ad-bfe7-956e063c0b27"

[[r2_buckets]]
binding = "R2"
bucket_name = "r2-automotora-mtg"

[vars]
ENVIRONMENT = "production"

[triggers]
crons = ["*/5 * * * *"]
